baseURL: 'https://sredevops.dev'
title: SREDevOps.dev
markdownEngine: goldmark
languageCode: es-CL
defaultContentLanguage: es
theme: sredevops

# disqusShortname: elclaustrocl
url: 'https://sredevops.dev'
name: SREDevOps.dev
description: Queremos construir "Curiosidad Continua" y "Comunidades como Soporte"
enableRobotsTXT: true
enableGitInfo: true
enableInlineShortcodes: true
markup:
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true
      xhtml: true
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
        type: true
        subfolder: true
        date: true
        draft: true
        slug: true
        categories: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: false
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false  
    noClasses: true
    tabWidth: 2

permalinks:
  posts: /:title/
  pages: /:title/
  section: /:section/
  taxonomies: /:section/:slug/
#   year: /:year/
#   month: /:year/:month/
#   day: /:year/:month/:day/
  tag: /tag/:slug/
  category: /categoria/:slug/
  # series: /series/:slug/
  # noticias: /noticias/:slug/

resourceDir: ./resources
DefaultContentLanguage: es
# Paginate: 10
PygmentsCodeFences: true
PygmentsStyle: one-dark
# paginate: 10
rssLimit: 10
copyright: >-
  This work is licensed under a Creative Commons Attribution-NonCommercial 4.0
  International License.
# archetypeDir: ./archetypes
contentDir: ./content
dataDir: ./data
layoutDir: ./layouts
publishDir: ./public
buildDrafts: false
buildFuture: true
buildExpired: true
canonifyURLs: true
enableEmoji: true
enableMissingTranslationPlaceholders: false
disableRSS: false
disableSitemap: false
disable404: false
disableHugoGeneratorInject: true
# permalinks:
#   posts: '/posts/:year/:month/:title/'
#   pages: '/:title/'
#   taxonomies: '/:title/'
#   home: '/index.html'
#   section: '/:section/'
#   tag: '/tag/:slug/'
#   category: '/category/:slug/'

author:
  name: Nicolás Georger
blackfriday:
  hrefTargetBlank: false
taxonomies:
  tag: tags
  category: categorias
  series: series
  noticia: noticias
params:
  logo:
    path: 'logo-h.png'
    alt: 'SREDevOps.dev'
    maxWidth: '500px'
  portait:
    path: 'logo-h.png'
    alt: 'SREDevOps.dev'
    maxWidth: '500px'
  dateform: '2 Jan 2006'
  dateformShort: 2 Jan
  dateformNum: '01-02-2006'
  dateformNumTime: '2006-01-02 15:04'
  description: >-
    Promovemos la cultura SRE/DevOps, con enfoque en Chile y América Latina, a
    través de facilitar comunidades y contextos de apoyo, orientación y
    aprendizaje.
  keywords: "sre, SREDevOps, dev, chile, español, site reliability engineering"
  # logo: 'logo-h.png'
  # homeSubtitle: >-
  disableReadOtherPosts: false
  enableThemeToggle: false
  enableSharingButtons: true
  enableGlobalLanguageMenu: false
  customCSS: []
  customJS: []
  justifyContent: true
  footer:
    trademark: false
    rss: false
    copyright: false
    author: false
    # topText:  SREDevOps.devx

    bottomText:
      - >-
        Construído con <a href="http://gohugo.io">Hugo</a>
      - >-
        Theme basado en <a href="https://github.com/rhazdon/hugo-theme-hello-friend-ng">@rhazdon</a>
  favicon:
    color:
      mask: '#1b1c1d'
      msapplication: '#1b1c1d'
      theme: '#1b1c1d'
  # logo:
  #   logoMark: 'usuario@sredevops.dev$'
  #   logoText: cd $HOME
  #   logoHomeLink: /

  social:
    # - name: twitter
    #   url: 'https://twitter.com/'
    - name: email
      url: 'mailto:info@sredevops.dev'
    - name: github
      url: 'https://github.com/sredevopsdev'
    - name: linkedin
      url: 'https://www.linkedin.com/company/sredevops/'
    # - name: stackoverflow
    #   url: 'https://www.stackoverflow.com/'
    - name: youtube
      url: 'https://www.youtube.com/@srdevopsdev'
    - name: discord
      url: 'https://discord.gg/bK9rXFTvpk'
    - name: rss
      url: '/index.xml'

languages:
  es:
    subtitle: Queremos construir "Curiosidad Continua" y "Comunidades como Soporte"
    weight: 1
menu:
  main:
    - identifier: home
      name: Inicio
      url: /
    - identifier: comunidad-discord
      name: Discord
      url: https://discord.gg/bK9rXFTvpk
    - identifier: github
      name: Github
      url: 'https://github.com/sredevopsdev'
    # - identifier: about
    #   name: About
    #   url: about/
    # - identifier: posts
    #   name: Posts
    #   url: posts/
