name: stale repo identifier

on:
#  push:
#  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron: '3 2 1 * *'

jobs:
  build:
    name: stale repo identifier
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run stale_repos tool
      uses: docker://ghcr.io/github/stale_repos:v1
      env:
        GH_TOKEN: ${{ secrets.GHCR_PASS }}
        ORGANIZATION: sredevopsdev
        INACTIVE_DAYS: 100

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: Stale repository report
        content-filepath: ./stale_repos.md
        assignees: ${{ secrets.GHCR_USER }}
        
