name: Get starred repositories
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      username:
        description: "GitHub username"
        required: true
        default: "${GITHUB_ACTOR}"
        type: string


jobs:
  get-starred-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get starred repositories
        uses: actions/github-script@v6
        id: get-starred-repos
        with:
          script: |
            import json
            import requests

            username = "${{ github.event.inputs.username }}"

            response = requests.get(
                f"https://api.github.com/users/{username}/starred"
            )

            starred_repos = json.loads(response.content)

            print(starred_repos)
      - name: Group repositories by category
        uses: actions/github-script@v6
        with:
          script: |
            const starredRepos = ${{ steps.get-starred-repos.outputs.result }};
            const categories = [
              "api",
              "cli",
              "css",
              "design",
              "devops",
              "docker",
              "dotfiles",
              "elixir",
              "frontend",
              "go",
              "graphql",
              "javascript",
              "linter",
              "node",
              "php",
              "python",
              "react",
              "ruby",
              "rust",
              "swift",
              "typescript",
              "vim",
              "vscode",
            ];

            const groupedRepos = categories.reduce(
              (grouped, category) => ({
                ...grouped,
                [category]: starredRepos.filter((repo) =>
                  repo.description?.toLowerCase().includes(category)
                ),
              }),
              {}
            );

            console.log(JSON.stringify(groupedRepos));
        id: group-repositories-by-category
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: "${{ github.token }}"
          commit-message: "Add starred repositories"
          title: "Add starred repositories"
          body: |
            This pull request was automatically generated by [get-starred-repos]( 